- name: mysql installation
  hosts: mysql
  become: yes
  tasks:
  - name: installatioiin for
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: enable service and start
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes 
  
  - name: connect mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.gonew.io
    register: mysql_info

  - name: print the output
    ansible.builtin.debug:
      msg: "Mysql information: {{ mysql_info }}"